spring:
  application:
    name: Parser
  datasource:
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/access?allowPublicKeyRetrieval=true&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver